# These are supported funding model platforms

github: hxr404
patreon: hxr404
open_collective: hxr404
custom: ["https://github.com/hxr404/hxr404/raw/main/hxr404_monero.png", "https://github.com/hxr404/hxr404/blob/main/freeDonate.md"]
